trigger:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app/*

stages:
  - stage: stage_test_01
    jobs:
      - job:
        pool:
          name: Azure Pipelines
          vmImage: ubuntu-latest

        steps:
          - bash:
              echo "Main pipeline"
            displayName: "Main pipeline"
             

  - stage: stage_test_02
    jobs:
      - job:
        pool:
          name: Azure Pipelines
          vmImage: ubuntu-latest

        steps:
          - bash:
              echo "Main pipeline"
            displayName: "child pipeline"