trigger:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app/*

pr:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app

# variables:
#   ${{ if eq(variables['Build.Reason.PullRequest'])}}

stages:
  - stage: develop
    displayName: "develop"
    jobs:
      - job:
        pool:
          name: Azure Pipelines
          vmImage: ubuntu-latest

        steps:
          - script: |
              echo "the followin is the reason why"
              echo Build.Reason