trigger:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app/*

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

steps:
  - bash:
      echo "Main pipeline"
    displayName: "Main pipeline"