trigger:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app/*

pr:
  branches:
      include:
      - '*'
  paths:
     include:
     - force-app

stages:
  - stage: build
    jobs:
      - job:
        pool:
          ##vmImage: ubuntu-latest
          # name: default
          name: Azure Pipelines
          vmImage: ubuntu-latest
        steps:
          - task: UseNode@1
          - task: Npm@1
            inputs:
              command: custom
              customCommand: install sfdx-cli --global

          - bash:
              echo "build steps to be done (Node, cli and so on. Will be used to set the project)"
            displayName: "build"
             

  - stage: sourceCodeValidation
    displayName: "Source Code Validation"
    jobs:
      - deployment: 
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
              
              - task: Npm@1
                inputs:
                    command: custom
                    customCommand: install sfdx-cli --global

              - bash: 
                  touch access.key
                displayName: "Temp file for auth url file creation  __ org 1"

              - bash:    
                  echo $SF_URL > access.key
                env:
                  SF_URL: $(SalesforceOrgAuthUrl)
                displayName: "Write url to the temp file  __ org 1"


              - bash: 
                  sfdx force:auth:sfdxurl:store -f "access.key" -a salesforce.org
                displayName: "Connect to the Salesforce  __ org 1"

              - bash: 
                  sfdx force:org:display -u salesforce.org
                displayName: "Salesforce org connection doublecheck  __ org 1"

  - stage: deploymentToBuildOrg
    displayName: "Deployment to Build org"
    jobs:
      - deployment: 
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
              
              - task: Npm@1
                inputs:
                    command: custom
                    customCommand: install sfdx-cli --global

              - bash: 
                  touch access.key
                displayName: "Temp file for auth url file creation  __ org 1"

              - bash:    
                  echo $SF_URL > access.key
                env:
                  SF_URL: $(SalesforceOrgAuthUrl)
                displayName: "Write url to the temp file  __ org 1"


              - bash: 
                  sfdx force:auth:sfdxurl:store -f "access.key" -a salesforce.org
                displayName: "Connect to the Salesforce  __ org 1"

              - bash: 
                  sfdx force:org:display -u salesforce.org
                displayName: "Salesforce org connection doublecheck  __ org 1"



  - stage: deploymentToQAOrg
    displayName: "Deployment to QA org"
    jobs:
      - deployment: 
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
              
              - task: Npm@1
                inputs:
                    command: custom
                    customCommand: install sfdx-cli --global

              - bash: 
                  touch access.key
                displayName: "Temp file for auth url file creation  __ org 1"

              - bash:    
                  echo $SF_URL > access.key
                env:
                  SF_URL: $(SalesforceOrgAuthUrl)
                displayName: "Write url to the temp file  __ org 1"


              - bash: 
                  sfdx force:auth:sfdxurl:store -f "access.key" -a salesforce.org
                displayName: "Connect to the Salesforce  __ org 1"

              - bash: 
                  sfdx force:org:display -u salesforce.org
                displayName: "Salesforce org connection doublecheck  __ org 1"