trigger:
  branches:
      include:
      - develop
  paths:
     include:
     - force-app/*

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

steps:
  - bash:
      echo "Child pipeline"
    displayName: "Child pipeline"